- hosts: all
  become: true
  tasks:
      - name: elasticearch 
        command: kubectl apply -f /home/ubuntu/elasticsearch-ss.yaml
      - name: logstash 
        command: kubectl apply -f /home/ubuntu/logstash-deployment.yaml     
#       - name: filebeat 
#         command: kubectl apply -f /home/ubuntu/filebeat-ds.yaml    
      - name: metricbeat 
        command: kubectl apply -f /home/ubuntu/metricbeat-ds.yaml    
      - name: kibana 
        command: kubectl apply -f /home/ubuntu/kibana-deployment.yaml
